kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apisix-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: apisix-ingress-controller
    namespace: apisix-client-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apisix-clusterrole

